### ISSUE TITLE
Have player automatically climb up short steps

### ISSUE THREAD

**Issue by PopeRigby** [Scrapjack-Studios/slayer#39]
https://godotforums.org/discussion/19140/rigidbody-player-class-walking-up-stairs

**Comment by julianhenrywilson** [comment]
I fixed it with a elif statement

**Comment by julianhenrywilson** [comment]
It did not fix it

**Comment by julianhenrywilson** [comment]
Moved auto climb to input function so that fixed it. It feels kinda wonky tho.
